In [2]:
% matplotlib inline
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import tree
import sklearn
import algorithms as my_algs

from sklearn.ensemble import (RandomForestClassifier, ExtraTreesClassifier)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
data = pd.read_csv('data/car.data', names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])

In [4]:
for name in data.columns:
    data[name] = pd.Categorical(data[name]).codes
data.head()

buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [5]:
Y = data['class']
X = data.drop('class', axis=1).as_matrix()
# X.head()

In [11]:
t = tree.DecisionTreeClassifier()
print(my_algs.score_model_with_cross_validation(
    t,
    X,
    Y
))
my_algs.score_confusion_matrix(t, X, Y)

0.980316574808


array([[ 92,   3,   1,   0],
       [  1,  12,   0,   0],
       [  0,   0, 309,   0],
       [  0,   0,   0,  14]])

In [7]:
my_algs.score_model_with_cross_validation(
    tree.DecisionTreeClassifier(criterion='entropy'),
    X,
    Y
)

0.98380830756822135

In [9]:
t = RandomForestClassifier(200)
print(my_algs.score_model_with_cross_validation(
    t,
    X,
    Y
))
my_algs.score_confusion_matrix(t, X, Y)

0.980914773491


array([[105,   1,   6,   1],
       [  3,  10,   0,   0],
       [  4,   0, 291,   0],
       [  0,   0,   0,  11]])

In [10]:
t = ExtraTreesClassifier(200)
print(my_algs.score_model_with_cross_validation(
    t,
    X,
    Y
))
my_algs.score_confusion_matrix(t, X, Y)

array([[ 95,   2,   3,   1],
       [  1,  15,   0,   0],
       [  3,   0, 296,   0],
       [  0,   0,   0,  16]])