In [7]:
% matplotlib inline
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import tree
import sklearn
import algorithms as my_algs

from sklearn.ensemble import (RandomForestClassifier, ExtraTreesClassifier)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
data = pd.read_csv(
    'data/bank-additional/bank-additional-full.csv',
    sep=';'
)
data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [9]:
for name in data.select_dtypes(include=['object', np.int64]).columns:
    data[name] = pd.Categorical(data[name]).codes
for name in data.select_dtypes(include=[np.float64]).columns:
    data[name] = (data[name] - data[name].min()) / (data[name].max() - data[name].min())
data.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   39    3        1          0        0        0     0        1      6   
1   40    7        1          3        1        0     0        1      6   
2   20    7        1          3        0        2     0        1      6   
3   23    0        1          1        0        0     0        1      6   
4   39    7        1          3        0        0     2        1      6   

   day_of_week ...  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1 ...         0     26         0         1        0.9375   
1            1 ...         0     26         0         1        0.9375   
2            1 ...         0     26         0         1        0.9375   
3            1 ...         0     26         0         1        0.9375   
4            1 ...         0     26         0         1        0.9375   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0        0.698753        0.60251   0.957379     0.859735  0  
1        0.698753        0.60251   0.957379     0.859735  0  
2        0.698753        0.60251   0.957379     0.859735  0  
3        0.698753        0.60251   0.957379     0.859735  0  
4        0.698753        0.60251   0.957379     0.859735  0  

[5 rows x 21 columns]

In [10]:
Y = data['y']
X = data.drop('y', axis=1).as_matrix()

In [11]:
my_algs.score_model_with_split(
    tree.DecisionTreeClassifier(),
    X,
    Y
)

[[8487  525]
 [ 624  661]]


0.88841410119452269

In [12]:
my_algs.score_model_with_split(
    tree.DecisionTreeClassifier(criterion='gini'),
    X,
    Y
)

[[8601  502]
 [ 571  623]]


0.89579489171603377

In [29]:
my_algs.score_model_with_split(
    RandomForestClassifier(100, max_depth=9, min_samples_leaf=6, min_samples_split=4),
    X,
    Y
)

[[8927  712]
 [ 192  466]]


0.91220743905992041

In [44]:
my_algs.score_model_with_split(
    ExtraTreesClassifier(100),
    X,
    Y
)

[[8894  661]
 [ 244  498]]


0.91211032339516362