In [1]:
% matplotlib inline
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import tree
import sklearn
import algorithms as my_algs

from sklearn.ensemble import (RandomForestClassifier, ExtraTreesClassifier)

In [14]:
features = train_Y = pd.read_csv('data/UCI_HAR_Dataset/features.txt', delim_whitespace=True, header=None)

train_X = pd.read_csv('data/UCI_HAR_Dataset/train/X_train.txt', delim_whitespace=True, names=features[1].ravel())
train_Y = pd.read_csv('data/UCI_HAR_Dataset/train/y_train.txt', delim_whitespace=True, header=None)
train_X, train_Y = sklearn.utils.shuffle(train_X, train_Y)
print(train_Y.columns)
test_X = pd.read_csv('data/UCI_HAR_Dataset/test/X_test.txt', delim_whitespace=True, names=features[1].ravel())
test_Y = pd.read_csv('data/UCI_HAR_Dataset/test/y_test.txt', delim_whitespace=True, header=None)

train_Y = train_Y.as_matrix().ravel()
test_Y = test_Y.as_matrix().ravel()

Int64Index([0], dtype='int64')


array([5, 5, 5, ..., 2, 2, 2])

In [3]:
from sklearn import metrics
def test_model(model, model_name):
    model.fit(train_X, train_Y)
    train_score = model.score(train_X, train_Y)
    test_score = model.score(test_X, test_Y)
    print(metrics.confusion_matrix(model.predict(test_X), test_Y))
    print(f'Model: {model_name}')
    print('-----------------------------')
    print(f'train score: {train_score:.3f}')
    print(f'test score: {test_score:.3f}')
    print('\n')

In [4]:
test_model(sklearn.neighbors.KNeighborsClassifier(n_neighbors=11), 'Knn')

[[487  37  48   0   0   0]
 [  0 428  41   4   0   0]
 [  9   6 331   0   0   0]
 [  0   0   0 389  35   2]
 [  0   0   0  98 497   1]
 [  0   0   0   0   0 534]]
Model: Knn
-----------------------------
train score: 0.974
test score: 0.905




In [5]:
test_model(tree.DecisionTreeClassifier(), 'DecisionTreeClassifier')

[[435  75  26   0   0   0]
 [ 43 355  48   0   0   0]
 [ 18  41 346   0   0   0]
 [  0   0   0 375  73   0]
 [  0   0   0 116 459   0]
 [  0   0   0   0   0 537]]
Model: DecisionTreeClassifier
-----------------------------
train score: 1.000
test score: 0.851




In [6]:
kwargs = {
    'max_depth': 8,
    'min_samples_split': 4,
    'min_samples_leaf': 2
}
test_model(tree.DecisionTreeClassifier(**kwargs), f'DecisionTreeClassifier {list(kwargs.items())}')

[[470  75  11   0   0   0]
 [  9 365  57   0   0   0]
 [ 17  31 352   0   0   0]
 [  0   0   0 374  59   0]
 [  0   0   0 117 473   0]
 [  0   0   0   0   0 537]]
Model: DecisionTreeClassifier [('max_depth', 8), ('min_samples_split', 4), ('min_samples_leaf', 2)]
-----------------------------
train score: 0.973
test score: 0.872




In [7]:
test_model(tree.DecisionTreeClassifier(criterion='entropy'), 'DecisionTreeClassifier: entropy')

[[457  71  23   0   0   0]
 [ 15 354  47   0   0   0]
 [ 24  46 350   0   0   0]
 [  0   0   0 381  84   0]
 [  0   0   0 110 448   0]
 [  0   0   0   0   0 537]]
Model: DecisionTreeClassifier: entropy
-----------------------------
train score: 1.000
test score: 0.857




In [8]:
test_model(RandomForestClassifier(n_estimators=200), 'RandomForestClassifier')

[[478  37  21   0   0   0]
 [ 12 425  45   0   0   0]
 [  6   9 354   0   0   0]
 [  0   0   0 439  44   0]
 [  0   0   0  52 488   0]
 [  0   0   0   0   0 537]]
Model: RandomForestClassifier
-----------------------------
train score: 1.000
test score: 0.923




In [15]:
kwargs = {
    'n_estimators':400,
    'max_depth': 15,
    'min_samples_split': 10,
    'min_samples_leaf': 5
}
test_model(ExtraTreesClassifier(**kwargs), 'RandomForestClassifier')

[[483  20  28   0   0   0]
 [  4 445  45   1   0   0]
 [  9   6 347   0   0   0]
 [  0   0   0 427   7   0]
 [  0   0   0  62 525   0]
 [  0   0   0   1   0 537]]
Model: RandomForestClassifier
-----------------------------
train score: 0.998
test score: 0.938


